apiVersion: v1
kind: Service
metadata:
  name: matcha-backend-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/health-check-path: "/actuator/health"
spec:
  type: LoadBalancer
  selector:
    app: matcha-backend
  ports:
    - protocol: TCP
      port: 80        # external port 그대로 80 사용
      targetPort: 8080  # Pod 내부 포트
