apiVersion: v1
kind: Service
metadata:
  name: matcha-backend-service
spec:
  type: LoadBalancer
  selector:
    app: matcha-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
