apiVersion: apps/v1
kind: Deployment
metadata:
  name: matcha-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matcha-backend
  template:
    metadata:
      labels:
        app: matcha-backend
    spec:
      containers:
      - name: matcha-backend
        image: asia-northeast3-docker.pkg.dev/matcha-480312/matcha-repo/matcha-backend:latest
        ports:
        - containerPort: 8080
