name: Test Secrets
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: Print Secrets (masked)
      run: |
        echo "---- CHECKING SECRETS ----"
        echo "GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}"
        echo "GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}"
        echo "GKE_LOCATION: ${{ secrets.GKE_LOCATION }}"
        echo "GAR_REPO: ${{ secrets.GAR_REPO }}"
        echo "ServiceAccountKey: ${{ secrets.GCP_SA_KEY }}"
